### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by hz61p1**

### CODE REVIEW

**Comment by mkuf** [comment]
Please elaborate on what you are implementing here.

**Comment by hz61p1** [comment]
@mkuf 
1. Adding a linter brings in generally accepted guidelines when writing yaml files
2. Adding docker image overrides via environment variable, so that you don't have to edit docker compose files if you need a specific version

**Comment by mkuf** [comment]
Adding a linter seems like a good idea.  

---

If one wants to override the Image for a specific service, the existing `docker-compose.override.yaml` may be used. Do you have a specific usecase in mind, where this is not working?

**Comment by hz61p1** [comment]
@mkuf It works, but this way allows you to override at a higher level and not to copy-paste, but also to set the desired versions in one file (.env) or at the command line level

**Comment by hz61p1** [comment]
@mkuf I've updated the pr

**Comment by mkuf** [comment]
Merged, thanks!

**Pull request merged**
