### PR TITLE
Support input shaper

### PR DESCRIPTION
**Pull request by flynny75**
Install numpy and required packages to support input shaper

### CODE REVIEW

**Comment by mkuf** [comment]
Hello, 
thanks for your PR.

Your patch would increase the size of the runtime image by almost 300MB, which is quite a bit.
```
klipper                      resonance         608931ade7b7   37 minutes ago   810MB
klipper                      latest            8c2009fd317e   44 minutes ago   537MB
```
Given that not all packages are needed at runtime, I'd like to omit those from the runtime image.  
The apt packages you added are only used for the postprocessing script, which could be run in a different container or on the host itself.

Numpy on the other hand seems to be essential when running the `TEST_RESONANCES` GCODE, can you confirm this?

This also needs to be mentioned in the Readme, as the default way of measuring resonances with a RasperryPi described in the [Klipper Docs](https://www.klipper3d.org/Measuring_Resonances.html) does not work, because the Container has no access to the Pis GPIO.  

-Markus

**Comment by flynny75** [comment]
These are good suggestions, I have updated the branch to not include the additional apt packages, and updated the README.

**Comment by mkuf** [comment]
I'd like to add examples and also a compose file to simplify the calibration process.  
Could you provide CSVs, that I can use to test this? I currently don't have a printer, that is equipped with an accelerometer.

-Markus

**Comment by sbonnick** [comment]
Hey guys, I was just about to start looking creating a branch for this too. so glad to see someone is already on it. 

As an alternative, to using the PI GPIO I see you are also wiring directly to a octopus. For at least a sanity check, I am using nearly the exact same config (only probe points slightly different). So at least we know this is a repeatable config. I would suspect other common boards to also expose a SPI somewhere as well. So, great news, no Docker-compose file changes needed to allow for ADXL communication as long as its via the MCU.

My printer.cfg file has this in it:

`
[adxl345]
cs_pin: PA15
spi_bus: spi3
axes_map: x, z, -y

[resonance_tester]
accel_chip: adxl345
probe_points:
    175,175,20 # an example
`

Note, I intend to use "Auto_calibration" as well. This does still require numpy to be installed though as @mkuf was asking about.  But I think the plan to have any "additional" features be done outside of the container is a reasonable one. I would suspect the only thing to add to a compose in that case is a volume mapping to the csv files or parent directory.

**Comment by mkuf** [comment]
This has been implemented with https://github.com/mkuf/prind/commit/14b89b0b0b3711f166621dbf9f076960ade92a36. 
The Image is currently building: https://github.com/mkuf/prind/runs/7253269485?check_suite_focus=true

**Pull request closed without merging**
